version: "0.2"
files:
  - "**/*"
ignorePaths:
  - pnpm-lock.yaml
  - .git/
  - dist/
useGitignore: true
language: en, en-GB
allowCompoundWords: true
enableGlobDot: true
words:
  - aarch
  - aminya
  - Amnet
  - anotherproj
  - applellvm
  - ARGN
  - asan
  - buildtools
  - ccache
  - ccmake
  - choco
  - cmake
  - cmakelint
  - cmds
  - cond
  - CPATH
  - Cppcheck
  - cppcoreguidelines
  - CPPFLAGS
  - cpprc
  - ctest
  - Cuda
  - DCMAKE
  - deps
  - DOPT
  - dyld
  - dylib
  - Eigen
  - fargs
  - fcolor
  - fdiagnostics
  - ftime
  - gcovr
  - Graphviz
  - hwrap
  - kcov
  - LDFLAGS
  - libc
  - libcuda
  - libstdc
  - LPSTR
  - LPWSTR
  - mdfile
  - msbuild
  - msvc
  - msys
  - multilib
  - municode
  - mylib
  - myprogram
  - myproj
  - myproject
  - nothrow
  - nvcc
  - Opencppcoverage
  - pargs
  - pnpm
  - pwsh
  - rmrf
  - rpath
  - sccache
  - setx
  - shlib
  - suppr
  - TOLOWER
  - TOUPPER
  - ubsan
  - vcpkg
  - vcvarsall
  - visualc
  - visualcpp
  - VSCMD
  - VSINSTALLDIR
  - vsversion
  - Wcast
  - Wconversion
  - Wdouble
  - Wduplicated
  - Werror
  - Weverything
  - Wextra
  - Wformat
  - Wlogical
  - Wmisleading
  - Wnon
  - Wnull
  - Woverloaded
  - Wpedantic
  - Wshadow
  - Wsign
  - Wunused
  - Wuseless
  - xcrun
  - Yahyaabadi
  - "ARGN"
  - "CMAKE"
  - "fargs"
  - "shlib"
  - "vcpkg"
  - cppdbg
